gText_Birch_Welcome::
	.string "Hey there, kid!\p"
	.string "Good to even see you breathing\n"
	.string "after a fall like that!\p"
	.string "Wish I could give you some\n"
	.string "information about where you\n"
	.string "are, but I’m studying that myself.\p"
	.string "My name is Professor Paradigm,\n"
	.string "or that’s about as much as I remember.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This region has numerous\n"
	.string "Pokémon as does the rest of\n"
	.string "the world.\p"
	.string "But this region has a very\n"
	.string "unique ecosystem.\p"
	.string "I’ve given this region a name\n"
	.string "to make things simpler for\n"
	.string "research and the other inhabitants\n"
	.string "have adopted it as well.\p"
	.string	"This is “Tempora”!\p"
	.string "Oh, forgive me!\p"
	.string "I didn’t even bother to ask your name!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Would you kindly tell me?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah! Wonderful!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}{KUN}!\p"
	.string "Our adventure together awaits\n"
	.string "within these mysterious lands!\p"
	.string "to unfold.\p"
	.string "Follow me back to town!\n"
	.string "$"
